### ISSUE TITLE
Create a 'timings' window

### ISSUE THREAD

**Issue by Mixail132** [Mixail132/StandByer#47]
### Description:
A user might want to set a series of schedules for each device to automate the device switching based on the time. The issue is to create a window for these schedules.
### Tasks:
- [x] Create a window.
- [x] Fill the window with data.
- [x] Add the ability to change the time data from a drop-down menu.
- [x] Save the data from the drop-down menu to the '.env' file.
- [x] Add the 'timings' window to the 'exe' file builder.
