### ISSUE TITLE
Update the 'main' window if the schedule is set in the 'timing' window

### ISSUE THREAD

**Issue by Mixail132** [Mixail132/StandByer#63]
### Description:
If a user sets a schedule for any device to switch it on or off,  a special mark should be shown up in the main window.
The issue is to set this mark.
### Tasks:
- [ ] Add an attribute to keep True if the schedule is set.
- [ ] Define the attribute value depending on the schedule existence.
- [ ] Add a special 'clock' symbol to mark the state in the 'main' window.
- [ ] Update the symbol state in main window when saving the schedule.
