### ISSUE TITLE
Check if the timings are correct before saving

### ISSUE THREAD

**Issue by Mixail132** [Mixail132/StandByer#85]
### Description:
A user may set up incorrect timings. For example,  setting the on time at 16:00 and set the off time at 17:00.
This short period indicates the user doesn't know what they're doing. The period might harm the device.
The issue is to check whether the time period is correct.
### Tasks:
- [x] Check whether the ON time is not equal to the OFF time.
- [ ] Check whether the period between the ON time and the OFF time is more than 3 hours.
- [ ] Check whether the OFF time is set if the ON time is set.
