### ISSUE TITLE
Refactor the code and use GitHub actions

### ISSUE THREAD

**Issue by Mixail132** [Mixail132/StandByer#93]
### Description:
Refactor the code.
### Tasks:
- [ ] Add GitHub actions to run linters.
- [ ] Add the ability to run linters locally.
- [ ] Fix variables, classes, modules names.
- [ ] Check the code using linters.
- [ ] Remove unused code.
- [ ] Unignore the `.env` 
- [ ] Fix linters notes.
